apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: template-deploy
  name: template-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: template-pod
    spec:
      containers:
      - image: template:tag
        name: template-app
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 80
        
